
- helm-chart-name: "prometheus-opencost-exporter"
  helm-name: opencost
  helm-url: "https://prometheus-community.github.io/helm-charts"
  values: values.yaml
  secrets: false
  name: opencost
  namespace: opencost
- name: certmanager
  namespace: cert-manager
  manifest-url: https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml
- name: cnpg-operator
  namespace: cnpg-system
  sourcefile: cnpg-operator.yaml
