
- helm-chart-name: "prometheus-opencost-exporter"
  helm-name: opencost
  helm-url: "https://prometheus-community.github.io/helm-charts"
  values: values.yaml
  secrets: false
  name: opencost
  namespace: opencost
- name: certmanager
  namespace: cert-manager
  manifest-url: https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml
- name: cnpg-operator
  namespace: cnpg-system
  sourcefile: cnpg/cnpg-operator.yaml
- name: kyverno-policies
  namespace: default
  sourcefile: kyverno/kyverno-policies.yaml
- name: kyverno
  namespace: kyverno
  helm-chart-name: kyverno
  helm-name: kyverno
  helm-url: https://kyverno.github.io/kyverno/
  values: values.yaml
  secrets: false
- helm-chart-name: "prometheus"
  helm-name: prometheus
  helm-url: "https://prometheus-community.github.io/helm-charts"
  namespace: "monitoring"
  values: prometheus-values.yaml
  secrets: false
  name: prometheus
- helm-chart-name: "promtail"
  helm-name: promtail
  helm-url: "https://grafana.github.io/helm-charts"
  values: promtail-values.yaml
  secrets: false
  name: promtail
  namespace: "monitoring"
- name: dummy-secret-promtail
  namespace: monitoring
  sourcefile: promtail/dummy-secret-promtail.yaml
- name: trivy
  namespace: trivy-system
  helm-chart-name: trivy-operator
  helm-name: trivy-operator
  helm-url: https://aquasecurity.github.io/helm-charts
  values: values.yaml
  secrets: false