---
apiVersion: v1
kind: Secret
metadata:
  name: promtail-loki-tenant-credentials
  namespace: monitoring
type: Opaque
data:
  loki-tenant-pw-omni-devenv: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA==  # This is base64 encoded "A123examplesecretpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-user-credentials
  namespace: grafana
type: Opaque
data:
  grafana-admin-id: YWRtaW4= # This is base64 encoded "admin"
  grafana-admin-pw: cGFzc3dvcmQ= # This is base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-user-credential
  namespace: minio
type: Opaque
data:
  password: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA==  # This is base64 encoded "A123examplesecretpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: loki-minio-creds
  namespace: grafana-loki
type: Opaque
data:
  access_key_id: ZXh0ZXJuYWxTZWNyZXQ= # This is base64 encoded "externalSecret"
  #access_key_id: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA==  # This is base64 encoded "A123examplesecretpassword"
  secret_access_key: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA==  # This is base64 encoded "A123examplesecretpassword"
  loki_tenant_pw_demo: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA== # This is base64 encoded "A123examplesecretpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: mimir-minio-creds
  namespace: grafana-mimir
type: Opaque
data:
  access_key_id: ZXh0ZXJuYWxTZWNyZXQ= # This is base64 encoded "externalSecret"
  #access_key_id: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA==  # This is base64 encoded "A123examplesecretpassword"
  secret_access_key: QTEyM2V4YW1wbGVzZWNyZXRwYXNzd29yZA==  # This is base64 encoded "A123examplesecretpassword"
  .htpasswd: Y2x1c3Rlci1mb3JnZS1taW1pci10ZXN0LXVzZXI6JGFwcjEkbXN6R0hSZnUkZkRDaUEzMm9SZHRQOHRYR1RUbjJNMAo= # This is base64 encoded "cluster-forge-mimir-test-user:\$apr1\$mszGHRfu\$fDCiA32oRdtP8tXGTTn2M0" # Created from "htpasswd -cb htpasswd cluster-forge-mimir-test-user cluster-forge-mimir-test-pass"
